/*
 * FormulaInputDialog.java
 *
 * Created on June 30, 2008, 11:53 AM
 */

package kobdig.gui;

import kobdig.agent.AplTokenizer;
import kobdig.agent.Fact;
import kobdig.logic.Formula;
import kobdig.logic.PropositionalFormula;
import kobdig.logic.TruthDegree;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

/**
 * A dialog to allow the user to type in a formula and select
 * a degree of trust in [0, 1] for it.
 *
 * @author  Andrea G. B. Tettamanzi
 */
public class FormulaInputDialog extends javax.swing.JDialog
{
    /** The fact input by the user. */
    protected Fact fact;
    
    /** The trust degree selected by the user. */
    protected TruthDegree trust;
    
    /** A range model used to set and read slider values. */
    TruthDegreeRangeModel sliderModel;

    /** Creates new form FormulaInputDialog */
    public FormulaInputDialog(Frame owner)
    {
        super(owner, true);
        initComponents();
        // Initially disable the OK button:
        okButton.setEnabled(false);
        fact = null;
        trust = TruthDegree.NEUTRAL;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulaInputDialog = new javax.swing.JDialog();
        formulaText = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        sliderModel = new TruthDegreeRangeModel(0.0, 1.0);
        trustSlider = new javax.swing.JSlider(sliderModel);
        trustLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        javax.swing.GroupLayout formulaInputDialogLayout = new javax.swing.GroupLayout(formulaInputDialog.getContentPane());
        formulaInputDialog.getContentPane().setLayout(formulaInputDialogLayout);
        formulaInputDialogLayout.setHorizontalGroup(
            formulaInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        formulaInputDialogLayout.setVerticalGroup(
            formulaInputDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        formulaText.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                formulaTextTextValueChanged(evt);
            }
        });

        label1.setText("Formula:");

        label2.setText("Trust degree:");

        trustSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trustSliderStateChanged(evt);
            }
        });

        trustLabel.setText("0.5");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(trustSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(trustLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(formulaText, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formulaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(trustSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trustLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Returns the fact entered by the user.
 */
Fact getFact()
{
    return fact;
}

TruthDegree getTrust()
{
    return trust;
}
    
private void formulaTextTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_formulaTextTextValueChanged
// TODO add your handling code here:
    try
    {
        // Use a buffered reader with default buffer size
        Reader r = new BufferedReader(new StringReader(formulaText.getText()));
        AplTokenizer st = new AplTokenizer(r);
        st.nextToken();
        Formula phi = new PropositionalFormula(st);
        fact = new Fact(phi);
    }
    catch(IOException e)
    {
        fact = null;
        // TODO perhaps, show a tooltip with the error
    }
    okButton.setEnabled(fact!=null);
}//GEN-LAST:event_formulaTextTextValueChanged

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    // TODO add your handling code here:
    setVisible(false);
    dispose();
}//GEN-LAST:event_okButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    fact = null;
    okButtonActionPerformed(evt);
}//GEN-LAST:event_cancelButtonActionPerformed

private void trustSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trustSliderStateChanged
    trust = new TruthDegree(sliderModel.getActualValue());
    trustLabel.setText(trust.toString());
}//GEN-LAST:event_trustSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JDialog formulaInputDialog;
    private java.awt.TextField formulaText;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel trustLabel;
    private javax.swing.JSlider trustSlider;
    // End of variables declaration//GEN-END:variables

}
